QUALITY_PRESETS = {
    "480": {
        "codec": "libx264",
        "crf": 28,
        "preset": "veryfast",
        "subme": 2,
        "ref": 1,
        "me": "hex",
        "trellis": 0,
        "bframes": 3,
        "b_pyramid": 2,
        "deblock": "1,0",
        "weightp": 1,
        "weightb": 1,
        "mbtree": 1,
        "keyint": 250,
        "keyint_min": 23,
        "scenecut": 40,
        "aq": "1:1.00",
        "psy_rd": "1.00:0.00",
        "scale": "840:480",
        "audio_codec": "libopus",
        "audio_bitrate": "128k",
        "audio_samplerate": 48000,
        "extension": ".mkv",
    },
    "720": {
        "codec": "libx264",
        "crf": 26,
        "preset": "veryfast",
        "subme": 2,
        "ref": 1,
        "me": "hex",
        "trellis": 0,
        "bframes": 3,
        "b_pyramid": 2,
        "deblock": "1,0",
        "weightp": 1,
        "weightb": 1,
        "mbtree": 1,
        "keyint": 250,
        "keyint_min": 23,
        "scenecut": 40,
        "aq": "1:1.00",
        "psy_rd": "1.00:0.00",
        "scale": "1280:720",
        "audio_codec": "libopus",
        "audio_bitrate": "128k",
        "audio_samplerate": 48000,
        "extension": ".mkv",
    },
    "1080": {
        "codec": "libx264",
        "crf": 26,
        "preset": "ultrafast",
        "subme": 1,
        "ref": 1,
        "me": "dia",
        "trellis": 0,
        "bframes": 3,
        "b_pyramid": 2,
        "deblock": "1,0",
        "weightp": 1,
        "weightb": 1,
        "mbtree": 0,
        "keyint": 250,
        "keyint_min": 23,
        "scenecut": 40,
        "aq": "1:1.00",
        "psy_rd": "1.00:0.00",
        "analyse": "0x3:0x3",
        "scale": "1920:1080",
        "audio_codec": "libopus",
        "audio_bitrate": "128k",
        "audio_samplerate": 48000,
        "extension": ".mkv",
    },
    "hdrip": {
        "codec": "libx264",
        "preset": "medium",
        "subme": 8,
        "ref": 4,
        "me": "hex",
        "trellis": 2,
        "bframes": 0,
        "b_pyramid": 0,
        "deblock": "1,1",
        "weightp": 2,
        "mbtree": 1,
        "mixed_ref": 1,
        "chroma_qp_offset": -2,
        "keyint": 96,
        "keyint_min": 48,
        "scenecut": 40,
        "aq": "1:0.60",
        "psy_rd": "0.40:0.00",
        "mode": "2pass",
        "bitrate": "8000k",
        "maxrate": "12000k",
        "bufsize": "18000k",
        "scale": "1920:1080",
        "audio_codec": "aac",
        "audio_bitrate": "128k",
        "audio_samplerate": 44100,
        "extension": ".mkv",
    },
}


QUALITY_DISPLAY = {
    "480": "480p",
    "720": "720p",
    "1080": "1080p",
    "hdrip": "HDRip",
}


def get_preset(quality: str) -> dict:
    return QUALITY_PRESETS.get(quality, QUALITY_PRESETS["1080"])


def resolve_quality_key(rss_quality: str, override: str = "") -> str:
    if override and override in QUALITY_PRESETS:
        return override
    return rss_quality if rss_quality in QUALITY_PRESETS else "1080"


def quality_display(quality: str) -> str:
    return QUALITY_DISPLAY.get(quality, f"{quality}p" if quality else "480p")
